name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *' # Har 10 daqiqada ishlaydi
  workflow_dispatch: # Qo'lda ham ishga tushirish imkoniyati

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          curl -s https://fast-food-project-1.onrender.com > /dev/null
          echo "Ping yuborildi: $(date)"
